# -*- coding: utf-8 -*-
"""Abalone_Logistic_Regression_js

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_M7YsU5qxxxPAq5NkXUyrllOeaU9xW76
"""

# Step 1 - Import all required binaries for applying logistic regression to abalone data
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix

# Step 2 - Read data into a data frame
names = ['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight', 'Viscera weight', 'Shell weight', 'Rings']
df = pd.read_csv('/content/abalone.data', names=names, sep=',')

df.head()

# Step 3 - Preprocess the data
df.dtypes

df.isna().sum()

df = df.drop('Sex', axis=1)

df.columns

# Step 4 - Define X and y
X = df[['Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight']]
y = df['Rings']

# Step 5 - Split X and y into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=45)

# Step 6 - Create an object of the algorithm
lg = LogisticRegression(max_iter=300)

# Step 7 - Fit the data to the object
lg.fit(X_train, y_train)

lg.score(X_train,y_train)

print(lg.coef_)

print(lg.intercept_)



"""## Abalone Age Prediction using Logistic Regression

This notebook demonstrates the application of Logistic Regression to predict the age of abalone based on physical measurements.

### Data Loading and Preprocessing

The abalone dataset was loaded and the 'Sex' column was removed as it is a categorical feature that would require further encoding for this model. The remaining features are numerical.

### Model Training

A Logistic Regression model was trained on the preprocessed data.

### Model Evaluation

The model's performance was evaluated using the training data. The accuracy score and the model's coefficients and intercept are displayed in the notebook.
"""

print(f"Training Accuracy: {lg.score(X_train,y_train):.4f}")
print("\nModel Coefficients:")
print(lg.coef_)
print("\nModel Intercept:")
print(lg.intercept_)

"""### Interpretation of Results

The training accuracy indicates how well the model fits the training data. The coefficients show the relationship between each feature and the predicted rings (age). A positive coefficient suggests that an increase in the feature's value is associated with an increase in the predicted rings, while a negative coefficient suggests the opposite. The intercept is the predicted rings when all features are zero.

**Note:** Logistic Regression is typically used for binary or multi-class classification. Since the 'Rings' variable represents a count (which can be treated as a continuous variable), using Logistic Regression here might not be the most appropriate model. A regression model would likely be more suitable for predicting a continuous target variable like the number of rings. The current accuracy score is low, which could be due to this mismatch between the model and the nature of the target variable.
"""